# Site settings
title: Terry Contracting
email: Bob@terrycontracting.com
description: Construction Company 
url: http://jmessina1121.github.io 
github_username: jmessina1121

# Build settings
markdown: kramdown
permalink: pretty
