# Site settings
title: Jacob's Website
email:  jmessina@albany.edu
description: I am a boy 
url: jmessina1121.github.io 
github_username: jmessina1121

# Build settings
markdown: kramdown
permalink: pretty
