# Site settings
title: AlbanY ZBT
email: jmessina@albany.edu
description: I am a boy 
url: http://jmessina1121.github.io 
github_username: jmessina1121

# Build settings
markdown: kramdown
permalink: pretty
